name: "Terraform Infrastructure Change Management Pipeline with GitHub Actions"
permissions:
  contents: read
  id-token: write
on:
  workflow_dispatch

jobs: 
  terraform:
    runs-on: ubuntu-latest

    name: Terraform
    env:
      environment: staging 

    
    
    
    steps:
    
    
    
    - name: checkout 
      uses: actions/checkout@v2
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.CLIENT_ID }} 
        aws-secret-access-key: ${{ secrets.CLIENT_SECRET}} 
        aws-region: us-east-1


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7
        terraform_wrapper: false


    - name: Terraform Workflow
      working-directory: . # Use your environment folder
      run: |
        terraform init
        # terraform plan -out = demo-plan
        # terraform apply demo-plan --auto-approve
        terraform workspace new ${{ env.environment }}
        terraform workspace select ${{ env.environment }} && terraform plan 
        terraform workspace select ${{ env.environment }} && terraform apply -auto-approve
        # terraform workspace select ${{ env.environment }} && terraform destroy -auto-approve
      shell: bash